# -*- coding: utf-8 -*-
import random

str1 = ['Petonia','​Shobha de naranja','​Rojo and janu',
'​Naranja Rojo',
'​Grape soda',
'​SCarlet',
'Gorgeous blue',
'​Sugar plum',
'​Red',
'​Violet',
'​Bubblegum pink',
'​Grey',
'​Very plum',
'​Peach tea',
'​Peeche keen',
'Lavender tulle',
'​Caram Bano',
'Red clay',
'​Strawberry smoothie',
'​Princess purple',
'​Apricot',
'​Purple rain',
'​Mustard',
'​Techno Tangerine',
'​Peach smoothie',
'​Yellow orange',
'​Pumpkin',
'​Orange',
'​Mango madness',
'​Cinnamon and spice',
'​Duck duck yellow',
'​Really respiri',
'​Green yellow',
'​Green',
'​Totally teal',
'​Butter',
'​Strawberry milk',
'​Rocking red violet',
'​Ruby red',
'​Lucky green',
'​Wacky watermelon',
'​Pickle',
'​Yellow',
'kale salad',
'​Blush',
'​Yellowghgreen',
'​Under sea blue',
'​Evergreen',
'​Sunflower',
'​Pink lemonade',
'​Quicksilver',
'​Sili celery',
'Ruby red',
'Violet red',
'Spearmint gum',
'Ballet slippers',
'​pageant pink',
'Flamingo',
'​coral reef',
'Fruit punch',
'Lipstick',
'Black',
'Starry night',
'Graham crackerz',
'Blue',
'Blue Jeanz',
'Brown',
'Hot chilli pepper',
'​overalls',
'Blue green',
'Surfer blue',
'Blue mist',
'Mud',
'Choclate milk',
'Blue lake',
'Loony Lavender',
'Sweetheart',
'​mania teal',
'Blue lagoon',
'Clear blue sky',
'Nutty brown',
'Go for gold',
'Pepperoni',
'Hot fudge',
'Cool mint',
'Orange soda',
'Cerulean',
'Electric blue',
'Ketchup',
'Dawn sky',
'Indigo',
'Green benz',
'Icy blue']

def code():
    first_num = random.choice(str1)
    second_num = random.choice(str1)
    final_pair = first_num+"-"+second_num
    return final_pair

listt  =[]
for i in range(20):
    l1 = code()
    listt.append(l1.replace('\u200b', '').replace('\n', ''))

for j in listt:
    print(j)

